# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  archive:
    desc: build application
    cmds:
      - echo "increment build number"
      - agvtool next-version -all
      - echo "building app"
      - xcodebuild clean
      - xcodebuild  ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO -project capy.xcodeproj -scheme capy -configuration Release DSTROOT="/Users/jago/Code/capy-mac" archive

  install:
    desc: copy new app localy
    cmds:
      - echo "copy app to /Applications"
      - rm -rf /Applications/capy.app
      - mv Applications/capy.app /Applications
      
  release:
      desc: new release
      cmds:
        - task: archive
        - task: install
